from pyspark.sql.types import *

dependencies = StructType([
    StructField('ID', IntegerType()),
    StructField('Platform', StringType(), nullable=True),
    StructField('Project Name', StringType(), nullable=True),
    StructField('Project ID', IntegerType(), nullable=True),
    StructField('Version Number', StringType(), nullable=True),
    StructField('Version ID', StringType(), nullable=True),
    StructField('Dependency Name', StringType(), nullable=True),
    StructField('Dependency Platform', StringType(), nullable=True),
    StructField('Dependency Kind', StringType(), nullable=True),
    StructField('Optional Dependency', StringType(), nullable=True),
    StructField('Dependency Requirements', StringType(), nullable=True),
    StructField('Dependency Project ID', IntegerType(), nullable=True)
])

projects = StructType([
    StructField('ID', IntegerType()),
    StructField('Platform', StringType(), nullable=True),
    StructField('Name', StringType(), nullable=True),
    StructField('Created Timestamp', TimestampType(), nullable=True),
    StructField('Updated Timestamp', TimestampType(), nullable=True),
    StructField('Description', StringType(), nullable=True),
    StructField('Keywords', StringType(), nullable=True),
    StructField('Homepage URL', StringType(), nullable=True),
    StructField('Licenses', StringType(), nullable=True),
    StructField('Repository URL', StringType(), nullable=True),
    StructField('Versions Count', IntegerType(), nullable=True),
    StructField('SourceRank', IntegerType(), nullable=True),
    StructField('Latest Release Publish Timestamp', TimestampType(), nullable=True),
    StructField('Latest Release Number', StringType(), nullable=True),
    StructField('Package Manager ID', StringType(), nullable=True),
    StructField('Dependent Projects Count', IntegerType(), nullable=True),
    StructField('Language', StringType(), nullable=True),
    StructField('Status', StringType(), nullable=True),
    StructField('Last synced Timestamp', TimestampType(), nullable=True),
    StructField('Dependent Repositories Count', IntegerType(), nullable=True),
    StructField('Repository ID', IntegerType(), nullable=True)
])

projects_with_repository_fields = StructType([
    StructField('ID', IntegerType()),
    StructField('Platform', StringType(), nullable=True),
    StructField('Name', StringType(), nullable=True),
    StructField('Created Timestamp', TimestampType(), nullable=True),
    StructField('Updated Timestamp', TimestampType(), nullable=True),
    StructField('Description', StringType(), nullable=True),
    StructField('Keywords', StringType(), nullable=True),
    StructField('Homepage URL', StringType(), nullable=True),
    StructField('Licenses', StringType(), nullable=True),
    StructField('Repository URL', StringType(), nullable=True),
    StructField('Versions Count', IntegerType(), nullable=True),
    StructField('SourceRank', IntegerType(), nullable=True),
    StructField('Latest Release Publish Timestamp', TimestampType(), nullable=True),
    StructField('Latest Release Number', StringType(), nullable=True),
    StructField('Package Manager ID', StringType(), nullable=True),
    StructField('Dependent Projects Count', IntegerType(), nullable=True),
    StructField('Language', StringType(), nullable=True),
    StructField('Status', StringType(), nullable=True),
    StructField('Last synced Timestamp', TimestampType(), nullable=True),
    StructField('Dependent Repositories Count', IntegerType(), nullable=True),
    StructField('Repository ID', IntegerType(), nullable=True),
    StructField('Repository Host Type', StringType(), nullable=True),
    StructField('Repository Name with Owner', StringType(), nullable=True),
    StructField('Repository Description', StringType(), nullable=True),
    StructField('Repository Fork?', BooleanType(), nullable=True),
    StructField('Repository Created Timestamp', TimestampType(), nullable=True),
    StructField('Repository Updated Timestamp', TimestampType(), nullable=True),
    StructField('Repository Last pushed Timestamp', TimestampType(), nullable=True),
    StructField('Repository Homepage URL', StringType(), nullable=True),
    StructField('Repository Size', IntegerType(), nullable=True),
    StructField('Repository Stars Count', IntegerType(), nullable=True),
    StructField('Repository Language', StringType(), nullable=True),
    StructField('Repository Issues enabled?', BooleanType(), nullable=True),
    StructField('Repository Wiki enabled?', BooleanType(), nullable=True),
    StructField('Repository Pages enabled?', BooleanType(), nullable=True),
    StructField('Repository Forks Count', IntegerType(), nullable=True),
    StructField('Repository Mirror URL', StringType(), nullable=True),
    StructField('Repository Open Issues Count', StringType(), nullable=True),
    StructField('Repository Default branch', StringType(), nullable=True),
    StructField('Repository Watchers Count', IntegerType(), nullable=True),
    StructField('Repository UUID', StringType(), nullable=True),
    StructField('Repository Fork Source Name with Owner', StringType(), nullable=True),
    StructField('Repository License', StringType(), nullable=True),
    StructField('Repository Contributors Count', IntegerType(), nullable=True),
    StructField('Repository Readme filename', StringType(), nullable=True),
    StructField('Repository Changelog filename', StringType(), nullable=True),
    StructField('Repository Contributing guidelines filename', StringType(), nullable=True),
    StructField('Repository License filename', StringType(), nullable=True),
    StructField('Repository Code of Conduct filename', StringType(), nullable=True),
    StructField('Repository Security Threat Model filename', StringType(), nullable=True),
    StructField('Repository Security Audit filename', StringType(), nullable=True),
    StructField('Repository Status', StringType(), nullable=True),
    StructField('Repository Last Synced Timestamp', TimestampType(), nullable=True),
    StructField('Repository SourceRank', IntegerType(), nullable=True),
    StructField('Repository Display Name', StringType(), nullable=True),
    StructField('Repository SCM type', StringType(), nullable=True),
    StructField('Repository Pull requests enabled?', BooleanType(), nullable=True),
    StructField('Repository Logo URL', StringType(), nullable=True),
    StructField('Repository Keywords', StringType())
])

repositories = StructType([
    StructField('ID', IntegerType()),
    StructField('Host Type', StringType(), nullable=True),
    StructField('Name with Owner', StringType(), nullable=True),
    StructField('Description', StringType(), nullable=True),
    StructField('Fork?', BooleanType(), nullable=True),
    StructField('Created Timestamp', TimestampType(), nullable=True),
    StructField('Updated Timestamp', TimestampType(), nullable=True),
    StructField('Last pushed Timestamp', TimestampType(), nullable=True),
    StructField('Homepage URL', StringType(), nullable=True),
    StructField('Size', IntegerType(), nullable=True),
    StructField('Stars Count', IntegerType(), nullable=True),
    StructField('Language', StringType(), nullable=True),
    StructField('Issues enabled?', BooleanType(), nullable=True),
    StructField('Wiki enabled?', BooleanType(), nullable=True),
    StructField('Pages enabled?', BooleanType(), nullable=True),
    StructField('Forks Count', IntegerType(), nullable=True),
    StructField('Mirror URL', StringType(), nullable=True),
    StructField('Open Issues Count', StringType(), nullable=True),
    StructField('Default branch', StringType(), nullable=True),
    StructField('Watchers Count', IntegerType(), nullable=True),
    StructField('UUID', StringType(), nullable=True),
    StructField('Fork Source Name with Owner', StringType(), nullable=True),
    StructField('License', StringType(), nullable=True),
    StructField('Contributors Count', IntegerType(), nullable=True),
    StructField('Readme filename', StringType(), nullable=True),
    StructField('Changelog filename', StringType(), nullable=True),
    StructField('Contributing guidelines filename', StringType(), nullable=True),
    StructField('License filename', StringType(), nullable=True),
    StructField('Code of Conduct filename', StringType(), nullable=True),
    StructField('Security Threat Model filename', StringType(), nullable=True),
    StructField('Security Audit filename', StringType(), nullable=True),
    StructField('Status', StringType(), nullable=True),
    StructField('Last Synced Timestamp', TimestampType(), nullable=True),
    StructField('SourceRank', IntegerType(), nullable=True),
    StructField('Display Name', StringType(), nullable=True),
    StructField('SCM type', StringType(), nullable=True),
    StructField('Pull requests enabled?', BooleanType(), nullable=True),
    StructField('Logo URL', StringType(), nullable=True),
    StructField('Keywords', StringType())
])

repository_dependencies = StructType([
    StructField('ID', IntegerType()),
    StructField('Host Type', StringType(), nullable=True),
    StructField('Repository Name with Owner', StringType(), nullable=True),
    StructField('Repository ID', IntegerType(), nullable=True),
    StructField('Manifest Platform', StringType(), nullable=True),
    StructField('Manifest Filepath', StringType(), nullable=True),
    StructField('Git branch', StringType(), nullable=True),
    StructField('Manifest kind', StringType(), nullable=True),
    StructField('Optional', StringType(), nullable=True),
    StructField('Dependency Project Name', StringType(), nullable=True),
    StructField('Dependency Requirements', StringType(), nullable=True),
    StructField('Dependency Kind', StringType(), nullable=True),
    StructField('Dependency Project ID', IntegerType(), nullable=True),

])

tags = StructType([
    StructField('ID', IntegerType(), nullable=True),
    StructField('Host Type', StringType(), nullable=True),
    StructField('Repository Name with Owner', StringType(), nullable=True),
    StructField('Repository ID', IntegerType(), nullable=True),
    StructField('Tag Name', StringType(), nullable=True),
    StructField('Tag git sha', StringType(), nullable=True),
    StructField('Tag Published Timestamp', TimestampType(), nullable=True),
    StructField('Tag Created Timestamp', TimestampType(), nullable=True),
    StructField('Tag Updated Timestamp', TimestampType(), nullable=True),
])

versions = StructType([
    StructField('ID', IntegerType(), nullable=True),
    StructField('Platform', StringType(), nullable=True),
    StructField('Project Name', StringType(), nullable=True),
    StructField('Project ID', IntegerType(), nullable=True),
    StructField('Number', StringType(), nullable=True),
    StructField('Published Timestamp', TimestampType(), nullable=True),
    StructField('Created Timestamp', TimestampType(), nullable=True),
    StructField('Updated Timestamp', TimestampType())
])
